sudo: false
language: cpp
compiler: gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.8
        - g++-4.8

before_script:
    - cd ..
    - ls
    - git clone https://github.com/livingcreative/kcommon.git kcommon
    - mkdir build && cd build
    - cmake ../kcanvas/src

script: make